services:
  age:
    image: apache/age:latest
    profiles: ["age", "all"]
    ports:
      - "5432:5432"
    network_mode: "host"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  memgraph:
    image: memgraph/memgraph-mage:latest
    profiles: ["mem", "all"]
    ports:
      - "7445:7687"

  lab:
    image: memgraph/lab:latest
    profiles: ["mem", "all"]
    ports:
      - "3000:3000"

  adminer:
    profiles: ["age", "all"]
    image: adminer
    ports:
      - "8080:8080"
