FROM postgres:13-bullseye

# Update repositories and install AGE extension
RUN apt-get update
RUN apt-get install -y postgresql-13-age

# Create init script to load AGE extension
RUN mkdir -p /docker-entrypoint-initdb.d
RUN echo "CREATE EXTENSION IF NOT EXISTS age;" > /docker-entrypoint-initdb.d/01-age-init.sql

EXPOSE 5432
CMD ["postgres"]
