# Use a Python base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python code (e.g., age_test) into the container
COPY . /app

# Install required Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variable to make sure Python can find your modules
ENV PYTHONPATH="/app"

# Run the Python code
CMD ["python", "-m", "age_test.age_functionality_test"]
