site_name: Q-sip
nav:
   - Home: index.md
   - User: user.md
   - Developer: dev.md
   - Age: ohtu-muutokset_age.md
   - Neo4j: ohtu-muutokset_neo4j.md
   - About: about.md
theme: readthedocs
markdown_extensions:
  - md_in_html
