name: Fork unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests/test_graph_neo4j -t . -v
          python -m unittest discover -s tests/test_simple_backend -t . -v
          python -m unittest discover -s tests/tests_from_zxdb -t . -v
